"""Build assets/cadence-sample.js from the public Data Science Stack Exchange data dump.

Source: Stack Exchange, Inc. data dump, datascience.stackexchange.com, dump of 2024-04
(https://archive.org/details/stackexchange, file datascience.stackexchange.com.7z, last-modified
2024-04-07). Content licensed CC BY-SA (2.5 / 3.0 / 4.0 by post date). Only derived counts are
shipped: no post text, no titles, no user names or user ids.

What is kept: every ANSWER (PostTypeId 2) with an owner. A "creator" is an account with at least
20 answers. Time is cut into 28-day blocks from Monday 2014-05-12. For each creator and each block
in which they answered: number of answers, sum of answer scores (score = upvotes minus downvotes
at dump time). Creators are renumbered 0..N-1 in a seeded random order, so no row can be joined
back to a public profile by id. Site-wide totals per block (all answers, all accounts) are kept
for the platform-decline view.

Run:  python3 build-cadence-sample.py /path/to/datascience.stackexchange.com.7z
Needs: py7zr (pip install py7zr), pandas.
"""
import sys, json, random, xml.etree.ElementTree as ET, os, tempfile
import pandas as pd

SRC = sys.argv[1]
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "assets", "cadence-sample.js")
START = pd.Timestamp("2014-05-12")
MIN_ANSWERS = 20
SEED = 20240407

def load_posts(path):
    if path.endswith(".7z"):
        import py7zr
        tmp = tempfile.mkdtemp()
        with py7zr.SevenZipFile(path) as z:
            z.extract(path=tmp, targets=["Posts.xml"])
        path = os.path.join(tmp, "Posts.xml")
    rows = []
    for _, el in ET.iterparse(path):
        if el.tag == "row":
            a = el.attrib
            if a.get("PostTypeId") == "2" and a.get("OwnerUserId"):
                rows.append((int(a["OwnerUserId"]), a["CreationDate"], int(a["Score"])))
            el.clear()
    df = pd.DataFrame(rows, columns=["user", "date", "score"])
    df["date"] = pd.to_datetime(df["date"])
    return df

a = load_posts(SRC)
a["block"] = ((a["date"] - START).dt.days // 28).astype(int)
end_block = int(a["block"].max())
last_date = a["date"].max().strftime("%Y-%m-%d")

site = a.groupby("block").agg(k=("score", "size"), s=("score", "sum")).reindex(range(end_block + 1), fill_value=0)

counts = a.groupby("user").size()
users = sorted(counts[counts >= MIN_ANSWERS].index.tolist())
rng = random.Random(SEED)
rng.shuffle(users)
cid = {u: i for i, u in enumerate(users)}
b = a[a["user"].isin(cid)].copy()
b["c"] = b["user"].map(cid)
cb = b.groupby(["c", "block"]).agg(k=("score", "size"), s=("score", "sum")).reset_index().sort_values(["c", "block"])

data = {
    "source": "Data Science Stack Exchange data dump, 2024-04 (archive.org/details/stackexchange), CC BY-SA",
    "start": "2014-05-12", "blockDays": 28, "endBlock": end_block, "lastAnswer": last_date,
    "minAnswers": MIN_ANSWERS, "creators": len(users), "answers": int(cb["k"].sum()),
    "c": cb["c"].astype(int).tolist(), "b": cb["block"].astype(int).tolist(),
    "k": cb["k"].astype(int).tolist(), "s": cb["s"].astype(int).tolist(),
    "siteK": site["k"].astype(int).tolist(), "siteS": site["s"].astype(int).tolist(),
}
header = ("/* cadence-sample.js - real answer activity from the public Data Science Stack Exchange data dump\n"
          " * (2024-04, archive.org/details/stackexchange, CC BY-SA; derived counts shared under CC BY-SA 4.0).\n"
          " * " + str(len(users)) + " accounts with 20+ answers, renumbered in a seeded random order: no names, no ids, no text.\n"
          " * One row per creator per 28-day block in which they answered: c = creator, b = block (0 = 2014-05-12),\n"
          " * k = answers, s = summed answer score. siteK / siteS = every answer on the site, per block.\n"
          " * Generated by materials/build-cadence-sample.py with json.dumps. */\n")
with open(OUT, "w") as f:
    f.write(header + "window.CADENCE_SAMPLE = " + json.dumps(data, separators=(",", ":")) + ";\n")
print("wrote", OUT, os.path.getsize(OUT), "bytes;", len(users), "creators,", len(cb), "rows, end block", end_block, last_date)
